language: ruby
rvm:
 # - 2.2
 # - jruby
 # - rbx-2
before_script:
 - psql -c "create role ashigara with createdb login password 'ashigara';" -U postgres
 # - cp config/database.yml.travis config/database.yml
 - RAILS_ENV=test bundle exec rake db:create
