# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

mailgun_domain: "sandbox9be15ff104ff4b80b4db15ca868c2bb5.mailgun.org"
mailgun_user_name: "postmaster@sandbox9be15ff104ff4b80b4db15ca868c2bb5.mailgun.org"
mailgun_password: "810638453667ab7eb3e2e8df2099d524"

fb_app_id: '1405294702851940'
fb_app_secret: 'e79bfa0240263192d2357c968c1009c2'
gg_app_id: '191240187528-jqn6p07355q3cer91u6rm85a22612pvr.apps.googleusercontent.com'
gg_app_secret: 'C_vZ8nyNj2H6zpTT0dhhbvyS'
